version: 1.4.0

views:
  main:
    # Label
    - $: rect
      fill: ${{ theme.background }}
      x: 0
      y: -8
      width: ${{events.length * 16 }}
      height: 10
      label: step=${{ step }}, parent=${{ JSON.stringify(parent) }}, events.length=${{ events.length }}
      label-x: 0
      label-y: 4
      label-size: 4
      label-color: ${{ theme.foreground }}
      clear: true
      $info:
        step: ${{ step }}
        parent: ${{ parent }}
        events: ${{ events }}
    # Progress bar
    - $: rect
      fill: "${{ step == $.i ? color.blue : step >= $.i ? color.green : theme.foreground }}"
      alpha: "${{ step >= $.i ? 1 : 0.1 }}"
      x: ${{ $.i * 16 }}
      y: 0
      width: 16
      height: 2
      clear: true
      $for:
        $to: ${{ events.length }}

events:
  - { type: event, id: 0, pId: null }
  - { type: event, id: 1, pId: 0 }
  - { type: event, id: 2, pId: 1 }
  - { type: event, id: 3, pId: 2 }
  - { type: event, id: 4, pId: 3 }
  - { type: event, id: 5, pId: 4 }
  - { type: event, id: 6, pId: 5 }
  - { type: event, id: 7, pId: 6 }
  - { type: event, id: 8, pId: 7 }
  - { type: event, id: 9, pId: 8 }
